# Generated by Django 4.2.10 on 2024-04-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_special',
            field=models.BooleanField(default=True, verbose_name='مقاله ویژه'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('d', 'پیش نویس'), ('p', 'منشتر شده'), ('i', 'در حال بررسی'), ('b', 'عدم تایید')], max_length=1, verbose_name='وضعیت'),
        ),
    ]
